version: "3"

services:
  api:
    build: "./api/"
    restart: "always"
    env_file: 
      - "database.env"
    depends_on: 
      - "db"
    ports:
      - "5000:8000"
    networks:
      - "internal"

  db:
    image: "postgres:10"
    user: "postgres"
    restart: "always"
    env_file: 
      - "database.env"
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d:ro"
      - "./db/data:/var/lib/postgresql/data"
    networks:
      - "internal"
      
networks:
  internal:

