CREATE TABLE "drone" (
    "id"                          INT                           UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "name"                        TEXT                          NOT NULL,
    "brand"                       TEXT                          NOT NULL,
    "model"                       TEXT                          NOT NULL,
    "additional"                  TEXT
);

CREATE TABLE "user" (
    "id"                          INT                           UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "name"                        TEXT                          NOT NULL,
    "username"                    TEXT                          NOT NULL UNIQUE,
    "password"                    TEXT                          NOT NULL,
    "token"                       TEXT                          NOT NULL UNIQUE
);

CREATE TABLE "analytic" (
    "id"                          INT                           UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "name"                        TEXT                          NOT NULL,
    "description"                 TEXT                          NOT NULL,
    "location"                    POINT                         NOT NULL,
    "timestamp"                   TIMESTAMP                     NOT NULL
);

CREATE TABLE "picture" (
    "id"                          INT                           UNIQUE GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE "picture_analytic" (
    "picture"                     INT                           REFERENCES "picture" ("id"),
    "analytic"                    INT                           REFERENCES "analytic" ("id")
);

CREATE TABLE "drone_user" (
    "drone"                       INT                           REFERENCES "drone" ("id"),
    "user"                        INT                           REFERENCES "user" ("id"),

    PRIMARY KEY ("drone", "user")
);

CREATE TABLE "drone_picture" (
    "drone"                       INT                           REFERENCES "drone" ("id"),
    "picture"                     INT                           REFERENCES "picture" ("id"),
    "user"                        INT                           REFERENCES "user" ("id"),

    PRIMARY KEY ("drone", "picture", "user")
);
