CREATE TABLE "drone" (
    "id"                          INT                           UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "name"                        TEXT                          NOT NULL,
    "brand"                       TEXT                          NOT NULL,
    "model"                       TEXT                          NOT NULL,
    "additional"                  TEXT
);

CREATE TABLE "user" (
    "id"                          INT                           UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "name"                        TEXT                          NOT NULL,
    "username"                    TEXT                          NOT NULL UNIQUE
);

CREATE TABLE "analytics" (
    "id"                          INT                           UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "name"                        TEXT                          NOT NULL,
    "description"                 TEXT                          NOT NULL,
    "location"                    POINT                         NOT NULL,
    "timestamp"                   TIMESTAMP                     NOT NULL
);

CREATE TABLE "picture" (
    "id"                          INT                           UNIQUE GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE "picture_analytics" (
    "picture"                     INT                           REFERENCES "picture" ("id") ON DELETE CASCADE,
    "analytics"                   INT                           REFERENCES "analytics" ("id") ON DELETE CASCADE,

    PRIMARY KEY ("picture", "analytics")
);

CREATE TABLE "drone_user" (
    "drone"                       INT                           REFERENCES "drone" ("id") ON DELETE CASCADE,
    "user"                        INT                           REFERENCES "user" ("id") ON DELETE CASCADE,

    PRIMARY KEY ("drone", "user")
);

CREATE TABLE "drone_picture" (
    "drone"                       INT                           REFERENCES "drone" ("id") ON DELETE CASCADE,
    "picture"                     INT                           REFERENCES "picture" ("id") ON DELETE CASCADE,
    "user"                        INT                           REFERENCES "user" ("id") ON DELETE CASCADE,

    PRIMARY KEY ("drone", "picture", "user")
);
