### Fetch all users

GET http://localhost:5000/users

### Add user #1

POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "peter",
  "username": "null_pointer"
}

### Add user #2

POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "marco",
  "username": "marco_polo"
}

### Correctly modify existing user #1

PUT http://localhost:5000/users/1
Content-Type: application/json

{
  "name": "big boi",
  "username": "toivoton"
}

### Correctly modify existing user #2

PUT http://localhost:5000/users/2
Content-Type: application/json

{
  "name": "mandrake linux"
}

### Incorrectly modify existing user #1

PUT http://localhost:5000/users/2
Content-Type: application/json

{
  "id": 1,
  "name": "hallitus"
}

### Incorrectly modify existing user #2

PUT http://localhost:5000/users/9999
Content-Type: application/json

{
  "name": "nonexistent user"
}

### Correctly delete user 

DELETE http://localhost:5000/users/1

### Incorrectly delete user

DELETE http://localhost:5000/users/9999

