version: "3"

services:
  app:
    build: "."
    restart: "always"
    env_file: 
      - "database.env"
    depends_on: 
      - "db"
    ports:
      - "8080:8080"
    networks:
      - "internal"

  db:
    image: "postgres:9.6"
    restart: "always"
    env_file: 
      - "database.env"
    volumes:
      - "./db-init-scripts:/docker-entrypoint-initdb.d"
    networks:
      - "internal"
      
networks:
  internal:
